### ISSUE TITLE
cannot open the LAN homepage on Android devices

### ISSUE THREAD

**Issue by mantouwork** [rejetto/hfs#323]
Version 0.47.1
win11
cannot open the LAN homepage on Android devices

CMD：
server error FormidableError: plugin on index 0 failed with: Cannot read properties of undefined (reading 'on')
    at IncomingForm._parseContentType (C:\snapshot\hfs\dist\node_modules\formidable\src\Formidable.js:427:23)
    at IncomingForm.writeHeaders (C:\snapshot\hfs\dist\node_modules\formidable\src\Formidable.js:222:10)
    at IncomingForm.parse (C:\snapshot\hfs\dist\node_modules\formidable\src\Formidable.js:188:10)
    at serveGuiAndSharedFiles (C:\snapshot\hfs\dist\src\middlewares.js:116:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\snapshot\hfs\dist\node_modules\koa-mount\index.js:52:26
    at async throttler (C:\snapshot\hfs\dist\src\throttler.js:22:5)
    at async logMw (C:\snapshot\hfs\dist\src\log.js:87:5)
    at async headRequests (C:\snapshot\hfs\dist\src\middlewares.js:49:5) {
  code: undefined,
  httpCode: 500,
  idx: 0
}

**Comment by rejetto** [comment]
hey, I have no problems browsing on android and win11.
Please try to be more specific on what's your problem.
Try including screenshots or a video.

**Comment by rejetto** [comment]
the error reported in your message should be fixed in 0.47.3 but has nothing to do with your android problems.
This means that at the moment I have nothing to work with.
I'm closing this, but please reply here or (open another issue) when you find have additional information.
